class _BotCommands:
    def __init__(self):
        self.StartCommand = "start"
        self.MirrorCommand = "mirror"
        self.UnzipMirrorCommand = "unzip"
        self.TarMirrorCommand = "tarmirror"
        self.CancelMirror = "cancel"
        self.CancelAllCommand = "cancelall"
        self.ListCommand = "find"
        self.DeleteCommand = "del"
        self.StatusCommand = "status"
        self.AuthorizedUsersCommand = "users"
        self.AuthorizeCommand = "auth"
        self.UnAuthorizeCommand = "unauth"
        self.AddSudoCommand = "addsudo"
        self.RmSudoCommand = "rmsudo"
        self.PingCommand = "ping"
        self.RestartCommand = "restart"
        self.StatsCommand = "stats"
        self.HelpCommand = "help"
        self.LogCommand = "log"
        self.SpeedCommand = "speedtest"
        self.CloneCommand = "clone"
        self.CountCommand = "count"
        self.WatchCommand = "yt"
        self.TarWatchCommand = "taryt"
        self.UsageCommand = "usage"
        self.MediaInfoCommand = "mediainfo"
        self.ConfigMenuCommand = "config"
        self.ShellCommand = "shell"
        self.UpdateCommand = "update"


BotCommands = _BotCommands()
